// Link this test with fpu-reference.cpp / sonic_fpu_reference.hpp generated by
// prepare-fpu-runtime.py, plus the production FPU runtime/SDK. The candidate
// header comes from prepare-fpu-body.py. No test-only production probe or TLS.
// Compare ORIGINAL helper results after every operation, not only final values.
#include "katana/runtime/fpu.hpp"
#include "katana/runtime/exception.hpp"
#include "sonic_fpu_reference.hpp"
#include "sonic_fpu_body.hpp"
#include <algorithm>
#include <array>
#include <cfenv>
#include <cstdint>
#include <iostream>
#include <memory>
#include <optional>
#include <stdexcept>
#include <type_traits>
#include <utility>
#include <vector>
#include <xmmintrin.h>

using namespace katana::runtime;
using Op = FpuBinaryOperation;
using RefOp = SonicFpuReference_FpuBinaryOperation;
namespace {
void require(bool ok, const char* message) {
    if (!ok) throw std::runtime_error(message);
}
using Host = std::array<unsigned, 3>;
Host host() {
    return {_mm_getcsr(), static_cast<unsigned>(std::fegetround()),
            static_cast<unsigned>(std::fetestexcept(FE_ALL_EXCEPT))};
}
struct RestoreHost {
    std::fenv_t saved{};
    RestoreHost() { require(std::fegetenv(&saved) == 0, "cannot save host FP environment"); }
    ~RestoreHost() { static_cast<void>(std::fesetenv(&saved)); }
};
struct Fixture {
    CpuState cpu{.memory = Memory{0u}};
    std::shared_ptr<LinearMemoryDevice> ram = std::make_shared<LinearMemoryDevice>(128u);
    std::vector<std::uint64_t> reset_events;
    Fixture() {
        cpu.memory.map_region("sentinel", 0x0C000000u, ram);
        cpu.manual_reset_sink = {this, [](void* opaque, CpuState&, const ManualResetRequest& r) noexcept {
            auto& log = static_cast<Fixture*>(opaque)->reset_events;
            log.push_back(static_cast<std::uint64_t>(r.reason));
            log.push_back(static_cast<std::uint64_t>(r.cause));
            log.push_back(r.event_code); log.push_back(r.fault_address.has_value());
            log.push_back(r.fault_address.value_or(0)); log.push_back(r.instruction_pc);
            log.push_back(r.owner_pc); log.push_back(r.in_delay_slot);
            log.push_back(_mm_getcsr());
        }};
        reset_events.reserve(1024);
    }
    void seed(std::uint32_t fpscr, std::uint32_t salt) {
        reset_cpu(cpu, {0x8C63907Au, 0x8C001000u, 0x8C010000u, sr_md_mask, fpscr});
        reset_events.clear();
        for (unsigned i=0; i<16; ++i) {
            cpu.r[i] = 0x12340000u + salt + i;
            cpu.fr[i] = 0x3F000000u + ((salt+i*0x12345u)&0x7FFFFFu);
            cpu.xf[i] = 0xBF000000u + ((salt+i*0x23456u)&0x7FFFFFu);
        }
        for (unsigned i=0; i<cpu.r_bank.size(); ++i) cpu.r_bank[i]=0xBC000000u+i;
        cpu.pr=0x8C067C26u; cpu.gbr=0x8C001000u; cpu.fpul=0x13579BDFu;
        cpu.active_instruction_pc=(salt&1u)?0x8C63907Au:0u;
        cpu.active_instruction_physical_pc=0x0C63907Au;
        cpu.active_block_virtual_start=0x8C639066u;
        cpu.active_block_physical_start=0x0C639066u; cpu.active_block_size=0x374u;
        cpu.exception_generation=7; cpu.last_exception_generation=3;
        cpu.trap_pending=(salt&0x1000u)!=0; cpu.sleeping=true;
        cpu.attempted_guest_instructions=11; cpu.retired_guest_instructions=9;
        cpu.total_guest_cycles=123; cpu.pending_guest_cycles=19;
        cpu.last_memory_fault_provenance.valid=true;
        cpu.last_memory_fault_provenance.address=0xACEDu;
        // Seed instruction state as well as arithmetic state; body admission
        // rejects FD before any operation, independently of caller preflight.
        cpu.write_sr(sr_md_mask | ((salt&0x2000u)?sr_fd_mask:0u) |
                     ((salt&8u)?sr_rb_mask:0u) | ((salt&16u)?sr_bl_mask:0u) | (salt&3u));
        std::fill(ram->writable_bytes().begin(), ram->writable_bytes().end(), 0xA5);
    }
};

// Architectural state, exception provenance, accounting, sentinel RAM and
// callbacks. Avoid memcmp(CpuState): padding/backend identity is not state.
std::vector<std::uint64_t> snapshot(const Fixture& f) {
    const auto& c=f.cpu;
    std::vector<std::uint64_t> v; v.reserve(512);
    for(auto x:c.r) v.push_back(x);
    for(auto x:c.r_bank) v.push_back(x);
    for(auto x:c.fr) v.push_back(x);
    for(auto x:c.xf) v.push_back(x);
    for(auto x:c.utlb) {v.push_back(x.pteh);v.push_back(x.ptel);v.push_back(x.ptea);}
#define FIELD(x) v.push_back(static_cast<std::uint64_t>(c.x))
    FIELD(pc);FIELD(pr);FIELD(gbr);FIELD(vbr);FIELD(ssr);FIELD(spc);FIELD(sgr);
    FIELD(dbr);FIELD(tra);FIELD(tea);FIELD(expevt);FIELD(intevt);FIELD(pteh);
    FIELD(ptel);FIELD(ptea);FIELD(ttb);FIELD(mmucr);FIELD(tlb_load_count);
    FIELD(mach);FIELD(macl);FIELD(fpul);FIELD(fpscr);FIELD(sr);
    FIELD(t);FIELD(s);FIELD(q);FIELD(m);FIELD(trap_pending);
    FIELD(exception_generation);FIELD(last_exception_cause);FIELD(exception_in_delay_slot);
    FIELD(last_exception_instruction_pc);FIELD(last_exception_instruction_physical_pc);
    FIELD(last_exception_owner_pc);FIELD(last_exception_generation);
    FIELD(last_memory_fault_provenance.valid);FIELD(last_memory_fault_provenance.instruction_valid);
    FIELD(last_memory_fault_provenance.opcode_valid);FIELD(last_memory_fault_provenance.access_valid);
    FIELD(last_memory_fault_provenance.source_pc);FIELD(last_memory_fault_provenance.runtime_pc);
    FIELD(last_memory_fault_provenance.address);FIELD(last_memory_fault_provenance.opcode);
    FIELD(last_memory_fault_provenance.operation);FIELD(last_memory_fault_provenance.width);
    FIELD(sleeping);FIELD(last_prefetch_address);FIELD(prefetch_count);
    FIELD(attempted_guest_instructions);FIELD(retired_guest_instructions);
    FIELD(total_guest_cycles);FIELD(pending_guest_cycles);FIELD(active_instruction_pc);
    FIELD(active_instruction_physical_pc);FIELD(active_block_virtual_start);
    FIELD(active_block_physical_start);FIELD(active_block_size);FIELD(last_prefetch_was_store_queue);
#undef FIELD
    require(!c.address_space && !c.gdrom_services && !c.g1_bus, "backend unexpectedly installed");
    require(c.manual_reset_sink.context==&f && c.manual_reset_sink.callback, "reset sink changed");
    for(auto x:f.ram->bytes()) v.push_back(x);
    const auto& m=c.memory.performance_counters();
    v.push_back(m.indexed_region_hits);v.push_back(m.reference_region_probes);
    v.push_back(m.unobserved_accesses);v.push_back(m.observed_accesses);
    v.insert(v.end(),f.reset_events.begin(),f.reset_events.end());
    return v;
}

using Body = sonic::fpu_body::NontrappingSingleBody;
struct Step {
    Op operation;
    std::uint32_t n, m;
    unsigned pair = 0u;
    bool compare = false;
    bool seed_operands = true;
    unsigned toggle_mode = 0u;
};
constexpr std::array<std::pair<unsigned,unsigned>,3> registers{{{5u,2u},{2u,2u},{15u,0u}}};

template<Op Operation>
void binary(Body& body,unsigned pair) {
    switch(pair) {
    case 0:body.binary<Operation,5u,2u>();break;
    case 1:body.binary<Operation,2u,2u>();break;
    case 2:body.binary<Operation,15u,0u>();break;
    default:throw std::runtime_error("invalid register pair");
    }
}
void compare_equal(Body& body,unsigned pair) {
    switch(pair) {
    case 0:body.compare_equal<5u,2u>();break;
    case 1:body.compare_equal<2u,2u>();break;
    case 2:body.compare_equal<15u,0u>();break;
    default:throw std::runtime_error("invalid compare pair");
    }
}
void candidate_step(Body& body,const Step& step) {
    if(step.compare) {compare_equal(body,step.pair);return;}
    switch(step.operation) {
    case Op::Add:binary<Op::Add>(body,step.pair);break;
    case Op::Subtract:binary<Op::Subtract>(body,step.pair);break;
    case Op::Multiply:binary<Op::Multiply>(body,step.pair);break;
    case Op::Divide:binary<Op::Divide>(body,step.pair);break;
    }
}
std::vector<Step> sequence(unsigned kind,unsigned salt) {
    std::vector<Step> steps{
        {Op::Multiply,0x3FC00000u,0x3FA00000u},
        {Op::Add,0x3F800000u,0x33000000u},
        {Op::Subtract,0x3F800000u,0x3F800000u},
        {Op::Divide,0x3F800000u,0x40400000u},
        {Op::Add,0u,0x80000000u,0u,true},
        {Op::Multiply,0u,0x3FA00000u,1u},
        {Op::Add,0xBF800000u,0x3F800000u,2u,true},
        {Op::Add,0u,0u,0u,false,false},
    };
    steps[5].toggle_mode=fpscr_sz_mask;
    steps[6].toggle_mode=fpscr_fr_mask;
    if(kind==1u) {
        const std::array extras{
            Step{Op::Add,0x00800000u,0x80000001u}, // DN input flushing
            Step{Op::Multiply,0x00800000u,0x3F000000u}, // normal inputs, subnormal result
            Step{Op::Multiply,0x7F7FFFFFu,0x40000000u}, // overflow
            Step{Op::Divide,0x3F800000u,0u},
            Step{Op::Divide,0u,0u,1u},
            Step{Op::Add,0x7FA00001u,0x3F800000u},
            Step{Op::Subtract,0x7F800000u,0x7F800000u},
            Step{Op::Add,0x7FA00001u,0x7FC00001u,0u,true},
            Step{Op::Add,0x80000001u,0u,2u,true},
            Step{Op::Multiply,0x3F800001u,0x3F800003u},
            Step{Op::Add,0u,0u,0u,false,false},
        };
        steps.insert(steps.end(),extras.begin(),extras.end());
    } else if(kind==2u) {
        // Compare alone must also acquire/restore the original epoch on NaN.
        steps.insert(steps.begin(),Step{Op::Add,0x7FA00001u,0x3F800000u,0u,true});
        steps.push_back({Op::Divide,0x00800000u,0x7F000000u});
    } else if(kind==3u) {
        auto random=salt^0x638FF0u;
        for(unsigned i=0;i<32u;++i) {
            random=random*1664525u+1013904223u;const auto n=random;
            random=random*1664525u+1013904223u;const auto m=random;
            steps.push_back({static_cast<Op>(i%4u),n,m,i%3u,(i%7u)==0u,true,
                (i%5u)==0u?fpscr_fr_mask:(i%11u)==0u?fpscr_sz_mask:0u});
        }
    }
    return steps;
}
struct Outcome {
    std::vector<std::vector<std::uint64_t>> states;
    std::vector<Host> hosts;
    bool operator==(const Outcome&) const = default;
};

template<bool Reference>
Outcome execute(Fixture& fixture,const std::vector<Step>& steps,unsigned nesting,bool pure_integer) {
    using Epoch=std::conditional_t<Reference,SonicFpuReference_HostFpuExecutionEpoch,HostFpuExecutionEpoch>;
    Outcome out;
    const auto ambient=host();
    const auto body_rounding=fixture.cpu.fpscr&fpscr_rounding_mode_mask;
    CpuState outer_cpu{.memory=Memory{0u}};
    outer_cpu.fpscr=fpscr_dn_mask|(body_rounding^((nesting==2u || nesting==3u)?1u:0u));
    const auto run_body=[&] {
        const auto before=host();
        const auto prepare=[&](const Step& step) {
            if(step.toggle_mode) fixture.cpu.write_fpscr(fixture.cpu.fpscr^step.toggle_mode);
            if(step.seed_operands) {
                const auto [source,destination]=registers[step.pair];
                fixture.cpu.fr[destination]=step.n;fixture.cpu.fr[source]=step.m;
            }
        };
        if constexpr(Reference) {
            // Original helper oracle; the old native-body eager epoch remains
            // the reference for the exact returned host environment.
            Epoch epoch(fixture.cpu);
            for(const auto& step:steps) {
                prepare(step);
                const auto [source,destination]=registers[step.pair];
                if(step.compare) SonicFpuReference_fpu_compare_equal(fixture.cpu,source,destination);
                else SonicFpuReference_fpu_binary(fixture.cpu,static_cast<RefOp>(step.operation),source,destination);
                out.states.push_back(snapshot(fixture));
            }
        } else {
            const auto state_before=snapshot(fixture);
            Body body(fixture.cpu);
            require(body.admitted(),"eligible body declined");
            require(host()==before && snapshot(fixture)==state_before,"admission touched CPU/host");
            for(const auto& step:steps) {
                prepare(step);candidate_step(body,step);
                out.states.push_back(snapshot(fixture));
                if(pure_integer) require(host()==before,"integer-only body touched host FP state");
            }
        }
        require(host()==before,"body did not restore exact incoming host state");
        out.hosts.push_back(host());

        // Exercise the SAME implementation's retained ScopedHostRounding after
        // the body dies. An epoch TLS leak is observable here: the normal-input
        // underflow takes the host fallback and clears existing exception flags.
        Fixture probe;probe.seed(fpscr_dn_mask|(nesting?outer_cpu.fpscr:body_rounding),7u);
        probe.cpu.fr[2]=0x00800000u;probe.cpu.fr[5]=0x3F000000u;
        const auto probe_before=host();
        if constexpr(Reference)
            SonicFpuReference_fpu_binary(probe.cpu,RefOp::Multiply,5u,2u);
        else fpu_binary(probe.cpu,Op::Multiply,5u,2u);
        if(!nesting) require(host()==probe_before,"post-body helper leaked epoch TLS/host state");
        out.states.push_back(snapshot(probe));out.hosts.push_back(host());
    };
    if(!nesting) run_body();
    else {
        Epoch outer(outer_cpu);
        _mm_setcsr(_mm_getcsr()|0x20u);
        if(nesting==3u) {
            const auto nested_ambient=host();
            {Epoch inner(outer_cpu);run_body();}
            require(host()==nested_ambient,"nested body did not restore enclosing host flags");
        } else run_body();
    }
    require(host()==ambient,"outer epoch did not restore ambient host state");
    out.hosts.push_back(host());
    return out;
}

void test_case(unsigned mode,unsigned kind,unsigned nesting,unsigned salt) {
    const std::array rounds{FE_TONEAREST,FE_TOWARDZERO,FE_DOWNWARD,FE_UPWARD};
    require(std::fesetround(rounds[salt&3u])==0,"cannot seed host rounding");
    _mm_setcsr(0x1F80u|((salt&3u)<<13u)|(salt&0x3Fu)|((salt&4u)?0x8040u:0u));
    Fixture reference,candidate;
    for(auto* f:{&reference,&candidate}) {
        f->seed(mode,salt);f->cpu.trap_pending=false;f->cpu.sleeping=false;
        f->cpu.write_sr(f->cpu.sr&~sr_fd_mask);
    }
    const auto steps=sequence(kind,salt);
    const auto expected=execute<true>(reference,steps,nesting,kind==0u);
    const auto actual=execute<false>(candidate,steps,nesting,kind==0u);
    if(expected!=actual || snapshot(reference)!=snapshot(candidate)) {
        std::cerr<<"mode="<<mode<<" sequence="<<kind<<" nesting="<<nesting<<" salt="<<salt<<'\n';
        for(std::size_t i=0;i<std::min(expected.states.size(),actual.states.size());++i)
            if(expected.states[i]!=actual.states[i]) {std::cerr<<"first differing step="<<i<<'\n';break;}
        throw std::runtime_error("FPU body intermediate/original differential mismatch");
    }
}
} // namespace

int main() {
    try {
        RestoreHost restore;
        unsigned cases=0u;
        for(unsigned rounding:{0u,1u}) for(unsigned bank:{0u,fpscr_fr_mask})
            for(unsigned initial_status:{0u,fpscr_flag_mask|fpscr_cause_mask})
                for(unsigned kind=0u;kind<4u;++kind) for(unsigned nesting=0u;nesting<4u;++nesting) {
                    test_case(fpscr_dn_mask|rounding|bank|initial_status,kind,nesting,cases);
                    ++cases;
                }
        for(unsigned scenario=0u;scenario<12u;++scenario) {
            Fixture fixture;fixture.seed(fpscr_dn_mask,0u);fixture.cpu.sleeping=false;
            switch(scenario) {
            case 0:fixture.cpu.fpscr|=fpscr_pr_mask;break;
            case 1:fixture.cpu.fpscr|=fpscr_enable_invalid_mask;break;
            case 2:fixture.cpu.fpscr|=fpscr_enable_divide_by_zero_mask;break;
            case 3:fixture.cpu.fpscr|=fpscr_enable_overflow_mask;break;
            case 4:fixture.cpu.fpscr|=fpscr_enable_underflow_mask;break;
            case 5:fixture.cpu.fpscr|=fpscr_enable_inexact_mask;break;
            case 6:fixture.cpu.fpscr&=~fpscr_dn_mask;break;
            case 7:fixture.cpu.fpscr|=2u;break;
            case 8:fixture.cpu.fpscr|=3u;break;
            case 9:fixture.cpu.sr|=sr_fd_mask;break;
            case 10:fixture.cpu.trap_pending=true;break;
            case 11:fixture.cpu.sleeping=true;break;
            }
            const auto before=snapshot(fixture);const auto old_host=host();
            {Body body(fixture.cpu);require(!body.admitted(),"unsupported mode admitted");}
            require(snapshot(fixture)==before && host()==old_host,"declined body mutated state");
            ++cases;
        }
        std::cout<<"FPU_BODY_TEST_OK cases="<<cases
            <<" all_ops_intermediate_original_compare_alias_dn_rounding_flags_nested_epoch_tls_host_restore\n";
        return 0;
    } catch(const std::exception& error) {
        std::cerr<<"FPU_BODY_TEST_FAIL "<<error.what()<<'\n';return 1;
    }
}
