#include "sonic_menu_text.hpp"
#include <array>
namespace sonic::menu {
namespace {
struct Entry {std::string_view key;std::array<std::wstring_view,5> languages;};
// PAL text-language order. No OS-language or voice-language dependency.
constexpr Entry entries[]{
{"vibration_help",{L"ゲーム本来の振動の強さを調整します。0 にすると振動を無効にします。",L"Adjust the strength of the original game's vibration effects. Set to 0 to turn vibration off.",L"Réglez l’intensité des vibrations du jeu d’origine. Réglez sur 0 pour les désactiver.",L"Ajusta la intensidad de la vibración original del juego. Ponla a 0 para desactivarla.",L"Stelle die Stärke der originalen Vibrationseffekte ein. Mit 0 schaltest du die Vibration aus."}},
{"display_controlled",{L"ディスプレイに同期",L"Display controlled",L"Géré par l’écran",L"Según la pantalla",L"Bildschirmgesteuert"}},
{"fps_vsync_help",{L"VSync がオンの場合、画面の更新に同期します。保存された FPS 上限は VSync を無効にすると再び適用されます。",L"VSync On follows the display refresh. Your saved FPS limit applies again when VSync is turned off.",L"VSync activée suit la fréquence de l’écran. La limite FPS enregistrée s’applique de nouveau quand VSync est désactivée.",L"VSync activado sigue la frecuencia de la pantalla. El límite de FPS guardado se aplica de nuevo al desactivar VSync.",L"VSync Ein folgt der Bildschirmfrequenz. Dein gespeichertes FPS-Limit greift wieder, wenn du VSync ausschaltest."}},
{"vsync_help",{L"自動は描画方式の標準設定です。オンは画面の更新に同期します。オフではティアリングが発生する場合があります。変更には再起動が必要です。",L"Automatic keeps the renderer default. On synchronizes with the display. Off may allow tearing. Changing this requires a restart.",L"Automatique conserve le réglage du moteur. Activée synchronise l’affichage. Désactivée peut provoquer des déchirures. Redémarrage requis.",L"Automático conserva el ajuste del renderizador. Activado sincroniza la pantalla. Desactivado puede causar desgarros. Requiere reiniciar.",L"Automatisch behält den Renderer-Standard. Ein synchronisiert mit dem Bildschirm. Aus kann Bildrisse erlauben. Änderungen benötigen einen Neustart."}},
{"fps_help",{L"画面出力の上限です。ゲーム本来の速度は変わりません。補間せず、完成したゲーム画像を繰り返して表示します。",L"Limits display output without changing the original game speed. Completed game frames are repeated; movement is not interpolated.",L"Limite les images affichées sans changer la vitesse du jeu. Les images terminées sont répétées, sans interpolation des mouvements.",L"Limita las imágenes mostradas sin cambiar la velocidad del juego. Se repiten los fotogramas completos, sin interpolar el movimiento.",L"Begrenzt die Bildausgabe, ohne das originale Spieltempo zu ändern. Fertige Spielbilder werden wiederholt; Bewegungen werden nicht interpoliert."}},
{"title",{L"オプション",L"Options",L"Options",L"Opciones",L"Optionen"}},
{"close",{L"閉じる",L"Close",L"Fermer",L"Cerrar",L"Schließen"}},
{"game_stopped",{L"エラーのためゲームを終了しました。最後に保存したデータから再開できます。",L"The game stopped because of an error. You can restart from your last saved progress.",L"Le jeu s’est arrêté à cause d’une erreur. Reprenez depuis la dernière sauvegarde.",L"El juego se ha detenido por un error. Puedes continuar desde la última partida guardada.",L"Das Spiel wurde wegen eines Fehlers beendet. Du kannst beim letzten gespeicherten Fortschritt fortsetzen."}},
{"graphics_stopped",{L"描画エラーのためゲームを終了しました。別の描画方式を設定して再起動してください。",L"The game stopped because of a graphics error. Try restarting with the other renderer in sonic-config.exe.",L"Erreur graphique : essayez l’autre moteur de rendu dans sonic-config.exe, puis relancez le jeu.",L"Error gráfico: prueba el otro renderizador en sonic-config.exe y reinicia el juego.",L"Das Spiel wurde wegen eines Grafikfehlers beendet. Versuche den anderen Renderer in sonic-config.exe und starte erneut."}},
{"report_saved",{L"診断情報を保存しました。自動送信はされません。",L"Diagnostic report saved. Nothing has been uploaded.",L"Rapport enregistré. Aucun envoi n’a été effectué.",L"Informe guardado. No se ha enviado nada.",L"Diagnosebericht gespeichert. Es wurde nichts übertragen."}},
{"open_options",{L"ゲーム内オプションを開く",L"Open in-game options",L"Ouvrir les options du jeu",L"Abrir opciones del juego",L"Ingame-Einstellungen öffnen"}},
{"display",{L"画面",L"Display",L"Affichage",L"Pantalla",L"Bildschirm"}},
{"audio",{L"サウンド",L"Audio",L"Audio",L"Audio",L"Audio"}},
{"camera",{L"カメラ",L"Camera",L"Caméra",L"Cámara",L"Kamera"}},
{"controls",{L"操作",L"Controls",L"Commandes",L"Controles",L"Steuerung"}},
{"interface",{L"表示と言語",L"Interface & language",L"Interface et langue",L"Interfaz e idioma",L"Anzeige und Sprache"}},
{"profiles",{L"セーブとプロフィール",L"Saves & profiles",L"Sauvegardes et profils",L"Partidas y perfiles",L"Spielstände und Profile"}},
{"system",{L"PC設定",L"PC settings",L"Réglages PC",L"Ajustes de PC",L"PC-Einstellungen"}},
{"sound_test",{L"サウンドテスト",L"Sound Test",L"Test sonore",L"Prueba de sonido",L"Sound Test"}},
{"about",{L"このポートについて",L"About",L"À propos",L"Acerca de",L"Über"}},
{"back",{L"戻る",L"Back",L"Retour",L"Volver",L"Zurück"}},
{"apply",{L"適用",L"Apply",L"Appliquer",L"Aplicar",L"Übernehmen"}},
{"save",{L"設定を保存",L"Save settings",L"Enregistrer",L"Guardar ajustes",L"Einstellungen speichern"}},
{"discard",{L"変更を取り消す",L"Discard changes",L"Annuler les modifications",L"Descartar cambios",L"Änderungen verwerfen"}},
{"yes",{L"確認",L"Confirm",L"Confirmer",L"Confirmar",L"Bestätigen"}},
{"browse_files",{L"ファイルを選択",L"Browse files",L"Parcourir les fichiers",L"Examinar archivos",L"Datei auswählen"}},
{"import_browser",{L"インポートするセーブを選択",L"Choose a save to import",L"Choisir une sauvegarde à importer",L"Elegir partida para importar",L"Spielstand für den Import auswählen"}},
{"parent_folder",{L"上のフォルダーへ",L"Parent folder",L"Dossier parent",L"Carpeta superior",L"Übergeordneter Ordner"}},
{"story_data",{L"ストーリー",L"Story",L"Histoire",L"Historia",L"Story"}},
{"empty_profile",{L"まだセーブされていません",L"No saved progress yet",L"Aucune progression enregistrée",L"Todavía no hay progreso guardado",L"Noch kein gespeicherter Fortschritt"}},
{"default_profile",{L"オリジナルのプロフィール",L"Original profile",L"Profil d’origine",L"Perfil original",L"Ursprüngliches Profil"}},
{"no",{L"キャンセル",L"Cancel",L"Annuler",L"Cancelar",L"Abbrechen"}},
{"off",{L"オフ",L"Off",L"Non",L"No",L"Aus"}},
{"on",{L"オン",L"On",L"Oui",L"Sí",L"Ein"}},
{"original",{L"オリジナル",L"Original",L"Original",L"Original",L"Original"}},
{"recompiled",{L"Recompiled",L"Recompiled",L"Recompiled",L"Recompiled",L"Recompiled"}},
{"automatic",{L"自動",L"Automatic",L"Automatique",L"Automático",L"Automatisch"}},
{"never",{L"戻らない",L"Never",L"Jamais",L"Nunca",L"Nie"}},
{"game",{L"ゲーム設定を使用",L"Use game setting",L"Réglage du jeu",L"Ajuste del juego",L"Spieleinstellung"}},
{"seconds",{L"秒",L"s",L"s",L"s",L"s"}},
{"restart",{L"再起動が必要",L"Restart required",L"Redémarrage requis",L"Requiere reiniciar",L"Neustart erforderlich"}},
{"restart_question",{L"設定を保存してゲームを再起動しますか？ 未保存の進行は失われます。",L"Save settings and restart the game? Unsaved progress will be lost.",L"Enregistrer et redémarrer ? La progression non sauvegardée sera perdue.",L"¿Guardar y reiniciar? Se perderá el progreso sin guardar.",L"Speichern und Spiel neu starten? Ungesicherter Fortschritt geht verloren."}},
{"display_preview",{L"新しい画面設定を維持しますか？",L"Keep these display settings?",L"Conserver ces réglages d’affichage ?",L"¿Mantener estos ajustes de pantalla?",L"Diese Bildschirmeinstellungen beibehalten?"}},
{"rollback",{L"確認しない場合、自動的に元に戻ります。",L"Settings revert automatically without confirmation.",L"Sans confirmation, les réglages précédents seront rétablis.",L"Sin confirmación se restaurarán los ajustes anteriores.",L"Ohne Bestätigung werden die bisherigen Einstellungen automatisch wiederhergestellt."}},
{"live_help",{L"音量とカメラはすぐに反映されます。保存で次回も使用します。",L"Volume and camera changes apply immediately. Save to keep them next time.",L"Le volume et la caméra changent immédiatement. Enregistrez pour les conserver.",L"El volumen y la cámara cambian al instante. Guarda para conservarlos.",L"Lautstärke und Kamera ändern sich sofort. Zum dauerhaften Übernehmen speichern."}},
{"display_help",{L"画面の変更には再起動と確認が必要です。出力FPSはゲーム速度を変えません。",L"Display changes require restart and confirmation. Output FPS does not change game speed.",L"Les changements d’écran exigent redémarrage et confirmation. Les FPS ne changent pas la vitesse du jeu.",L"Los cambios de pantalla requieren reiniciar y confirmar. Los FPS no cambian la velocidad del juego.",L"Bildschirmänderungen benötigen Neustart und Bestätigung. Ausgabe-FPS ändern das Spieltempo nicht."}},
{"audio_help",{L"音楽・声・効果音を個別に調整します。動画の混合音声にはマスター音量が適用されます。",L"Adjust music, voices and effects separately. Mixed movie audio uses master volume.",L"Réglez musique, voix et effets. Le son mixé des vidéos suit le volume général.",L"Ajusta música, voces y efectos. El audio mezclado de vídeos usa el volumen general.",L"Musik, Stimmen und Effekte getrennt regeln. Gemischter Videoton folgt der Gesamtlautstärke."}},
{"camera_help",{L"Recompiledで右スティックとマウスを使用できます。イベントカメラは元のままです。",L"Recompiled enables right-stick and mouse look. Scripted cameras retain original control.",L"Recompiled permet la vue au stick droit et à la souris. Les scènes scriptées gardent leur caméra.",L"Recompiled permite mirar con stick derecho y ratón. Se conservan las cámaras de eventos.",L"Recompiled erlaubt Umsehen mit rechtem Stick und Maus. Geskriptete Kameras behalten ihre Steuerung."}},
{"controls_help",{L"操作を選択して割り当てます。矢印、Enter、Escでメニューを常に操作できます。",L"Select an action to bind it. Arrows, Enter and Escape always remain available in menus.",L"Sélectionnez une action à attribuer. Flèches, Entrée et Échap restent disponibles dans les menus.",L"Selecciona una acción para asignarla. Flechas, Intro y Esc siempre funcionan en menús.",L"Aktion zum Belegen auswählen. Pfeiltasten, Eingabe und Escape bleiben im Menü immer verfügbar."}},
{"capture",{L"キー、マウスボタン、コントローラーボタンを押してください。Escで割り当てかキャンセルを選べます。",L"Press a key, mouse button or controller button. Escape lets you choose to assign it or cancel.",L"Appuyez sur une touche ou un bouton. Échap permet de choisir entre attribuer cette touche et annuler.",L"Pulsa una tecla o botón de ratón o mando. Esc permite elegir entre asignarla o cancelar.",L"Taste, Maustaste oder Controllertaste drücken. Bei Escape kannst du zwischen Belegen und Abbrechen wählen."}},
{"bind_escape",{L"Escキーを割り当てますか？ キャンセルするには「いいえ」を選んでください。",L"Assign the Escape key? Choose No to cancel.",L"Attribuer la touche Échap ? Choisissez Non pour annuler.",L"¿Asignar la tecla Esc? Elige No para cancelar.",L"Escape belegen? Zum Abbrechen Nein wählen."}},
{"duplicate",{L"同じボタンの以前の割り当てを解除しますか？",L"Remove the previous assignment of this button?",L"Supprimer l’attribution précédente de ce bouton ?",L"¿Quitar la asignación anterior de este botón?",L"Die vorherige Belegung dieser Taste entfernen?"}},
{"profile_help",{L"ストーリーとチャオを同じスナップショットに保存します。ゲームが最後に保存した状態が対象です。",L"Story and Chao share one snapshot of the last in-game save. Unsaved gameplay is not included.",L"Histoire et Chao partagent la dernière sauvegarde du jeu. La progression non enregistrée est exclue.",L"Historia y Chao comparten la última partida guardada. No incluye progreso sin guardar.",L"Story und Chao werden gemeinsam vom letzten regulären Spielstand gesichert. Ungesicherter Fortschritt ist nicht enthalten."}},
{"overwrite",{L"現在のプロフィールを置き換えて再起動しますか？ 先にバックアップを作成します。",L"Replace this profile and restart? A backup is created first.",L"Remplacer ce profil et redémarrer ? Une sauvegarde de sécurité sera créée.",L"¿Reemplazar este perfil y reiniciar? Primero se creará una copia de seguridad.",L"Dieses Profil ersetzen und neu starten? Vorher wird eine Sicherung erstellt."}},
{"empty",{L"項目がありません",L"No entries",L"Aucune entrée",L"Sin entradas",L"Keine Einträge"}},
{"done",{L"完了",L"Done",L"Terminé",L"Hecho",L"Erledigt"}},
{"error",{L"操作を完了できませんでした。元のデータは保持されています。",L"The operation could not be completed. Existing data has been retained.",L"L’opération a échoué. Les données existantes ont été conservées.",L"No se pudo completar la operación. Se han conservado los datos existentes.",L"Der Vorgang konnte nicht abgeschlossen werden. Die vorhandenen Daten wurden erhalten."}},
{"title_only",{L"タイトルメニューから利用できます",L"Available from the title menu",L"Disponible depuis le menu titre",L"Disponible desde el menú principal",L"Im Titelmenü verfügbar"}},
{"resume",{L"続ける",L"Resume",L"Reprendre",L"Continuar",L"Fortsetzen"}},
{"paused_focus",{L"ウィンドウが非アクティブのため一時停止しました。",L"Paused because the window lost focus.",L"Pause : la fenêtre n’est plus active.",L"Pausa: la ventana dejó de estar activa.",L"Pausiert, weil das Fenster den Fokus verloren hat."}},
{"paused_controller",{L"コントローラーが切断されたため一時停止しました。",L"Paused because the controller disconnected.",L"Pause : la manette a été déconnectée.",L"Pausa: se desconectó el mando.",L"Pausiert, weil der Controller getrennt wurde."}},
{"diagnostics_help",{L"ビルド情報と設定のみを出力します。セーブや個人のパスは含まれず、自動送信もしません。",L"Exports build details and settings only. No saves, personal paths or automatic upload.",L"Exporte version et réglages uniquement, sans sauvegardes, chemins personnels ni envoi automatique.",L"Exporta versión y ajustes, sin partidas, rutas personales ni envío automático.",L"Exportiert nur Builddaten und Einstellungen. Keine Spielstände, persönlichen Pfade oder automatische Übertragung."}},
{"interpolation_help",{L"実験的な補間。安全に対応できる動きのみを補間し、イベントやテレポートではリセットします。",L"Experimental interpolation. Only safely matched movement is smoothed; events and teleports reset history.",L"Interpolation expérimentale limitée aux mouvements appariés. Événements et téléportations réinitialisent l’historique.",L"Interpolación experimental solo para movimientos compatibles. Eventos y teletransportes reinician el historial.",L"Experimentelle Interpolation für sicher zugeordnete Bewegungen. Ereignisse und Teleports setzen den Verlauf zurück."}},
{"renderer",{L"レンダラー",L"Renderer",L"Moteur graphique",L"Renderizador",L"Renderer"}},
{"resolution",{L"解像度",L"Resolution",L"Résolution",L"Resolución",L"Auflösung"}},
{"widescreen",{L"ワイド画面",L"Widescreen",L"Écran large",L"Pantalla panorámica",L"Breitbild"}},
{"window_mode",{L"ウィンドウモード",L"Window mode",L"Mode d’affichage",L"Modo de ventana",L"Fenstermodus"}},
{"windowed",{L"ウィンドウ",L"Windowed",L"Fenêtré",L"Ventana",L"Fenster"}},
{"borderless",{L"ボーダーレス",L"Borderless",L"Sans bordure",L"Sin bordes",L"Randlos"}},
{"fullscreen",{L"全画面",L"Fullscreen",L"Plein écran",L"Pantalla completa",L"Vollbild"}},
{"render_percent",{L"内部解像度",L"Render scale",L"Échelle de rendu",L"Escala de renderizado",L"Renderauflösung"}},
{"presentation_fps",{L"出力FPS制限",L"Output FPS limit",L"Limite FPS de sortie",L"Límite de FPS de salida",L"Ausgabe-FPS-Limit"}},
{"vsync",{L"垂直同期",L"VSync",L"Synchronisation verticale",L"Sincronización vertical",L"VSync"}},
{"anisotropy",{L"異方性フィルタリング",L"Anisotropic filtering",L"Filtrage anisotrope",L"Filtrado anisotrópico",L"Anisotrope Filterung"}},
{"interpolation",{L"動きの補間（実験的）",L"Motion interpolation (experimental)",L"Interpolation (expérimentale)",L"Interpolación (experimental)",L"Bewegungsinterpolation (experimentell)"}},
{"master_volume",{L"マスター音量",L"Master volume",L"Volume général",L"Volumen general",L"Gesamtlautstärke"}},
{"music_volume",{L"音楽",L"Music",L"Musique",L"Música",L"Musik"}},
{"voice_volume",{L"音声",L"Voices",L"Voix",L"Voces",L"Stimmen"}},
{"effects_volume",{L"効果音",L"Effects",L"Effets",L"Efectos",L"Effekte"}},
{"mute_background",{L"非アクティブ時にミュート",L"Mute in background",L"Couper le son en arrière-plan",L"Silenciar en segundo plano",L"Im Hintergrund stummschalten"}},
{"pause_focus_loss",{L"非アクティブ時に一時停止",L"Pause on focus loss",L"Pause si fenêtre inactive",L"Pausar al perder el foco",L"Bei Fokusverlust pausieren"}},
{"pause_controller_loss",{L"切断時に一時停止",L"Pause on controller disconnect",L"Pause si manette déconnectée",L"Pausar al desconectar el mando",L"Bei Controller-Trennung pausieren"}},
{"keyboard_enabled",{L"キーボードでP1を操作",L"Keyboard controls for P1",L"Clavier pour J1",L"Teclado para J1",L"Tastatursteuerung für P1"}},
{"camera_style",{L"カメラスタイル",L"Camera style",L"Style de caméra",L"Estilo de cámara",L"Kamerastil"}},
{"mouse_camera",{L"マウスでカメラ操作",L"Mouse camera",L"Caméra à la souris",L"Cámara con ratón",L"Mauskamera"}},
{"camera_sensitivity_x",{L"スティック横感度",L"Stick sensitivity X",L"Sensibilité stick X",L"Sensibilidad stick X",L"Stick-Empfindlichkeit X"}},
{"camera_sensitivity_y",{L"スティック縦感度",L"Stick sensitivity Y",L"Sensibilité stick Y",L"Sensibilidad stick Y",L"Stick-Empfindlichkeit Y"}},
{"mouse_sensitivity_x",{L"マウス横感度",L"Mouse sensitivity X",L"Sensibilité souris X",L"Sensibilidad ratón X",L"Maus-Empfindlichkeit X"}},
{"mouse_sensitivity_y",{L"マウス縦感度",L"Mouse sensitivity Y",L"Sensibilité souris Y",L"Sensibilidad ratón Y",L"Maus-Empfindlichkeit Y"}},
{"camera_invert_x",{L"左右反転",L"Invert camera X",L"Inverser caméra X",L"Invertir cámara X",L"Kamera X invertieren"}},
{"camera_invert_y",{L"上下反転",L"Invert camera Y",L"Inverser caméra Y",L"Invertir cámara Y",L"Kamera Y invertieren"}},
{"camera_deadzone",{L"カメラのデッドゾーン",L"Camera deadzone",L"Zone morte caméra",L"Zona muerta de cámara",L"Kamera-Deadzone"}},
{"movement_deadzone",{L"移動のデッドゾーン",L"Movement deadzone",L"Zone morte déplacement",L"Zona muerta de movimiento",L"Bewegungs-Deadzone"}},
{"swap_sticks",{L"左右スティックを交換",L"Swap sticks",L"Échanger les sticks",L"Intercambiar sticks",L"Sticks tauschen"}},
{"camera_return_seconds",{L"元のカメラに戻る時間",L"Return to original camera",L"Retour caméra originale",L"Volver a cámara original",L"Rückkehr zur Originalkamera"}},
{"vibration",{L"振動の強さ",L"Vibration strength",L"Intensité vibration",L"Intensidad de vibración",L"Vibrationsstärke"}},
{"glyph_style",{L"ボタン表示",L"Button symbols",L"Symboles des touches",L"Símbolos de botones",L"Tastensymbole"}},
{"keyboard",{L"キーボード",L"Keyboard",L"Clavier",L"Teclado",L"Tastatur"}},
{"bindings",{L"ボタン割り当て",L"Button bindings",L"Attribution des touches",L"Asignación de botones",L"Tastenbelegung"}},
{"reset_bindings",{L"標準の割り当てに戻す",L"Restore default bindings",L"Rétablir les touches par défaut",L"Restaurar controles predeterminados",L"Standardbelegung wiederherstellen"}},
{"subtitle_scale",{L"字幕サイズ",L"Subtitle size",L"Taille des sous-titres",L"Tamaño de subtítulos",L"Untertitelgröße"}},
{"subtitle_background",{L"字幕の背景",L"Subtitle background",L"Fond des sous-titres",L"Fondo de subtítulos",L"Untertitelhintergrund"}},
{"subtitles",{L"字幕",L"Subtitles",L"Sous-titres",L"Subtítulos",L"Untertitel"}},
{"text_language",{L"テキスト言語",L"Text language",L"Langue du texte",L"Idioma del texto",L"Textsprache"}},
{"voice_language",{L"音声言語",L"Voice language",L"Langue des voix",L"Idioma de voces",L"Sprachfassung"}},
{"automatic_backups",{L"自動バックアップ",L"Automatic backups",L"Sauvegardes automatiques",L"Copias automáticas",L"Automatische Sicherungen"}},
{"backup_limit",{L"保持するバックアップ数",L"Backups to retain",L"Copies à conserver",L"Copias a conservar",L"Anzahl Sicherungen"}},
{"backup_now",{L"今すぐバックアップ",L"Back up now",L"Sauvegarder maintenant",L"Crear copia ahora",L"Jetzt sichern"}},
{"restore_backup",{L"バックアップを復元",L"Restore backup",L"Restaurer une sauvegarde",L"Restaurar copia",L"Sicherung wiederherstellen"}},
{"switch_profile",{L"プロフィールを選択",L"Select profile",L"Choisir le profil",L"Seleccionar perfil",L"Profil auswählen"}},
{"new_profile",{L"新しいプロフィール",L"New profile",L"Nouveau profil",L"Nuevo perfil",L"Neues Profil"}},
{"export_save",{L"セーブをエクスポート",L"Export save",L"Exporter la sauvegarde",L"Exportar partida",L"Spielstand exportieren"}},
{"import_save",{L"セーブをインポート",L"Import save",L"Importer une sauvegarde",L"Importar partida",L"Spielstand importieren"}},
{"export_diagnostics",{L"診断情報をエクスポート",L"Export diagnostics",L"Exporter le diagnostic",L"Exportar diagnóstico",L"Diagnosebericht exportieren"}},
{"export_preview",{L"現在のストーリーとチャオのセーブをエクスポートしますか？",L"Export the current story and Chao save?",L"Exporter la sauvegarde actuelle de l’histoire et des Chao ?",L"¿Exportar la partida actual de historia y Chao?",L"Aktuellen Story- und Chao-Spielstand exportieren?"}},
{"up",{L"前へ",L"Move forward",L"Avancer",L"Avanzar",L"Vorwärts"}},
{"down",{L"後ろへ",L"Move backward",L"Reculer",L"Retroceder",L"Rückwärts"}},
{"left",{L"左へ",L"Move left",L"Aller à gauche",L"Ir a izquierda",L"Nach links"}},
{"right",{L"右へ",L"Move right",L"Aller à droite",L"Ir a derecha",L"Nach rechts"}},
{"a",{L"A：ジャンプ",L"A / Jump",L"A / Saut",L"A / Saltar",L"A / Springen"}},
{"b",{L"B：アクション",L"B / Action",L"B / Action",L"B / Acción",L"B / Aktion"}},
{"x",{L"X：アクション",L"X / Action",L"X / Action",L"X / Acción",L"X / Aktion"}},
{"y",{L"Y：アクション",L"Y / Action",L"Y / Action",L"Y / Acción",L"Y / Aktion"}},
{"start",{L"スタート / 一時停止",L"Start / Pause",L"Start / Pause",L"Start / Pausa",L"Start / Pause"}},
{"left_trigger",{L"左トリガー",L"Left trigger",L"Gâchette gauche",L"Gatillo izquierdo",L"Linker Trigger"}},
{"right_trigger",{L"右トリガー",L"Right trigger",L"Gâchette droite",L"Gatillo derecho",L"Rechter Trigger"}},
{"look_up",{L"上を見る",L"Look up",L"Regarder en haut",L"Mirar arriba",L"Nach oben schauen"}},
{"look_down",{L"下を見る",L"Look down",L"Regarder en bas",L"Mirar abajo",L"Nach unten schauen"}},
{"look_left",{L"左を見る",L"Look left",L"Regarder à gauche",L"Mirar izquierda",L"Nach links schauen"}},
{"look_right",{L"右を見る",L"Look right",L"Regarder à droite",L"Mirar derecha",L"Nach rechts schauen"}},
{"settings",{L"オプションを開く",L"Open options",L"Ouvrir les options",L"Abrir opciones",L"Optionen öffnen"}},
{"confirm",{L"メニューで決定",L"Menu confirm",L"Confirmer dans les menus",L"Confirmar en menú",L"Im Menü bestätigen"}},
{"cancel",{L"メニューで戻る",L"Menu back",L"Retour dans les menus",L"Volver en menú",L"Im Menü zurück"}},
{"save_before_sound",{L"サウンドテストを開く前に変更を保存してください。",L"Save your changes before opening Sound Test.",L"Enregistrez vos modifications avant le test sonore.",L"Guarda los cambios antes de abrir la prueba de sonido.",L"Bitte die Änderungen speichern, bevor du den Sound Test öffnest."}},
{"music_error",{L"オプションの音楽を読み込めませんでした。",L"Options music could not be loaded.",L"La musique des options n’a pas pu être chargée.",L"No se ha podido cargar la música de opciones.",L"Die Options-Musik konnte nicht geladen werden."}},
{"created",{L"プロフィールを作成しました。",L"Profile created.",L"Profil créé.",L"Perfil creado.",L"Profil erstellt."}},
{"active",{L"使用中",L"Active",L"Actif",L"Activo",L"Aktiv"}},
{"saved",{L"設定を保存しました。",L"Settings saved.",L"Paramètres enregistrés.",L"Ajustes guardados.",L"Einstellungen gespeichert."}},
{"keep_display",{L"この画面設定を使用しますか？ 確認しない場合は元に戻ります。",L"Keep these display settings? Without confirmation the previous settings return automatically.",L"Conserver ces réglages ? Sans confirmation, les réglages précédents seront rétablis.",L"¿Conservar estos ajustes? Sin confirmación se restaurarán automáticamente los anteriores.",L"Diese Bildschirmeinstellungen behalten? Ohne Bestätigung werden die bisherigen Einstellungen automatisch wiederhergestellt."}},
{"focus_pause",{L"ゲームが非アクティブになったため一時停止しました。",L"Paused because the game lost focus.",L"Pause : le jeu n’est plus au premier plan.",L"En pausa al pasar el juego a segundo plano.",L"Pausiert, weil das Spiel den Fokus verloren hat."}},
{"controller_pause",{L"コントローラーが切断されたため一時停止しました。",L"Paused because the controller disconnected.",L"Pause : la manette est déconnectée.",L"En pausa porque se ha desconectado el mando.",L"Pausiert, weil der Controller getrennt wurde."}},
{"no_backups",{L"使用できるスナップショットがありません。",L"No compatible snapshots found.",L"Aucun instantané compatible trouvé.",L"No se han encontrado copias compatibles.",L"Keine passenden Sicherungen gefunden."}},
{"operation_error",{L"操作を完了できませんでした。空き容量とアクセス権を確認してください。",L"The operation could not be completed. Check free space, file access and file compatibility.",L"Impossible de terminer. Vérifiez l’espace libre, les droits d’accès et la compatibilité du fichier.",L"No se pudo completar. Comprueba espacio libre, permisos y compatibilidad del archivo.",L"Der Vorgang konnte nicht abgeschlossen werden. Bitte freien Speicher, Dateizugriff und Dateikompatibilität prüfen."}},
{"backup_status",{L"バックアップの状態",L"Backup status",L"État des copies",L"Estado de las copias",L"Sicherungsstatus"}},
{"backup_waiting",{L"セーブを待機中",L"Waiting for save",L"En attente",L"En espera",L"Wartet auf Spielstand"}},
{"backup_saved",{L"保存済み",L"Saved",L"Enregistrée",L"Guardada",L"Gesichert"}},
{"backup_failed",{L"失敗",L"Failed",L"Échec",L"Error",L"Fehlgeschlagen"}},
{"backup_cleanup_pending",{L"保存済み・整理待ち",L"Saved; cleanup pending",L"Copie OK ; nettoyage",L"Guardada; sin limpiar",L"Gesichert; Bereinigung offen"}},
{"backup_failed_help",{L"バックアップに失敗しました。既存のセーブは変更していません。空き容量とアクセス権を確認し、再度バックアップしてください。",L"Backup failed. Existing saves were not overwritten. Check disk space and folder access, then use Back up now to retry.",L"Échec de la copie. Les sauvegardes existantes sont intactes. Vérifiez l’espace libre et les droits du dossier, puis réessayez.",L"Error de copia. Las partidas existentes están intactas. Comprueba el espacio libre y el acceso a la carpeta, y vuelve a intentarlo.",L"Sicherung fehlgeschlagen. Vorhandene Spielstände bleiben unverändert. Speicherplatz und Ordnerzugriff prüfen, dann erneut sichern."}},
{"backup_cleanup_help",{L"最新のバックアップは保存済みです。古いコピーを削除できません。フォルダーのアクセス権を確認してください。",L"The latest backup is safe. Older copies could not be removed. Check access to the backup folder.",L"La dernière copie est conservée. D’anciennes copies n’ont pas pu être supprimées. Vérifiez l’accès au dossier.",L"La última copia está a salvo. No se pudieron borrar copias antiguas. Comprueba el acceso a la carpeta.",L"Die neueste Sicherung ist gespeichert. Alte Kopien konnten nicht entfernt werden. Zugriff auf den Sicherungsordner prüfen."}},
{"audio_status",{L"音声出力の状態",L"Audio output status",L"État de la sortie audio",L"Estado de salida de audio",L"Status der Audioausgabe"}},
{"audio_idle",{L"未使用",L"Inactive",L"Inactive",L"Inactiva",L"Nicht aktiv"}},
{"audio_connected",{L"接続済み",L"Connected",L"Connectée",L"Conectada",L"Verbunden"}},
{"audio_silent_retrying",{L"無音・再接続中",L"Silent; reconnecting",L"Muette ; reconnexion",L"Sin sonido; reconectando",L"Stumm; verbinde erneut"}},
{"audio_partial_retrying",{L"一部無音・再接続中",L"Partial; reconnecting",L"Partielle ; reconnexion",L"Parcial; reconectando",L"Teilweise; verbinde erneut"}},
{"audio_restart_required",{L"ゲームの再起動が必要",L"Restart game",L"Redémarrer le jeu",L"Reiniciar el juego",L"Spiel neu starten"}},
{"audio_silent_help",{L"音声出力を使用できないため、無音で再生を続けます。自動的に再接続します。",L"No working audio output is available. Playback continues silently while the game retries the connection.",L"Aucune sortie audio disponible. La lecture continue sans son pendant la reconnexion automatique.",L"No hay salida de audio disponible. La reproducción sigue sin sonido mientras el juego intenta reconectarse.",L"Keine funktionierende Audioausgabe verfügbar. Das Spiel läuft stumm weiter und versucht automatisch, die Verbindung wiederherzustellen."}},
{"audio_partial_help",{L"一部の音声を出力できません。自動的に再接続します。",L"Some audio is unavailable. The game will retry the connection automatically.",L"Une partie du son est indisponible. Le jeu tentera de se reconnecter automatiquement.",L"Parte del audio no está disponible. El juego intentará reconectarse automáticamente.",L"Ein Teil der Audioausgabe ist ausgefallen. Das Spiel versucht automatisch, die Verbindung wiederherzustellen."}},
{"audio_restart_help",{L"一部の音声を安全に再接続できません。進行状況を保存してからゲームを再起動してください。",L"Some audio could not reconnect safely. Save your progress and restart the game to restore all sound.",L"Une partie du son n’a pas pu être rétablie. Sauvegardez votre progression, puis redémarrez le jeu.",L"No se pudo restablecer parte del audio. Guarda tu progreso y reinicia el juego para recuperar todo el sonido.",L"Ein Teil der Audioausgabe konnte nicht sicher verbunden werden. Fortschritt speichern und das Spiel für vollständigen Ton neu starten."}},
};
}
std::wstring_view text(std::string_view key,int language) noexcept {
    for(const auto& e:entries)if(e.key==key)return e.languages[language>=0 && language<5?language:1];
    return L"?";
}
}
