// Generated by import-native-hook-boundaries.ps1. Do not edit.
// Private Sonic Adventure PAL v1.003 legacy-exact boundaries only.
// Each entry remains contingent on a fresh Katana full-function proof.
// Requirements identity: sha256:da224de6cdc32ea724b28054a406cce001e4f0e49d7b7cbf1c699aa1f66cab72

#pragma once

#include <array>
#include "katana/runtime/game_project.hpp"

namespace sonic_adventure::private_data {

inline constexpr std::array<katana::runtime::GameProjectFunctionBoundary, 12u> legacy_exact_reexport_boundaries{
    katana::runtime::GameProjectFunctionBoundary{0x8C06C000u, 110u, "sa_legacy_exact_host_timing_owner_8c06c000"},
    katana::runtime::GameProjectFunctionBoundary{0x8C10EDA4u, 40u, "sa_legacy_exact_transfer_ta_system_owner_8c10eda4"},
    katana::runtime::GameProjectFunctionBoundary{0x8C10FA88u, 14u, "sa_legacy_exact_transfer_ta_system_owner_8c10fa88"},
    katana::runtime::GameProjectFunctionBoundary{0x8C602496u, 26u, "sa_legacy_exact_platform_interrupt_state_owner_8c602496"},
    katana::runtime::GameProjectFunctionBoundary{0x8C6024B0u, 40u, "sa_legacy_exact_platform_interrupt_state_owner_8c6024b0"},
    katana::runtime::GameProjectFunctionBoundary{0x8C6044E8u, 12u, "sa_legacy_exact_transfer_ta_system_owner_8c6044e8"},
    katana::runtime::GameProjectFunctionBoundary{0x8C640862u, 260u, "sa_legacy_exact_transfer_ta_system_owner_8c640862"},
    katana::runtime::GameProjectFunctionBoundary{0x8C640D22u, 272u, "sa_legacy_exact_transfer_ta_system_owner_8c640d22"},
    katana::runtime::GameProjectFunctionBoundary{0x8C641B00u, 86u, "sa_legacy_exact_transfer_ta_system_owner_8c641b00"},
    katana::runtime::GameProjectFunctionBoundary{0x8C646730u, 102u, "sa_legacy_exact_platform_interrupt_state_owner_8c646730"},
    katana::runtime::GameProjectFunctionBoundary{0x8C6509E0u, 112u, "sa_legacy_exact_transfer_ta_system_owner_8c6509e0"},
    katana::runtime::GameProjectFunctionBoundary{0x8C653580u, 76u, "sa_legacy_exact_platform_interrupt_state_owner_8c653580"},
};

} // namespace sonic_adventure::private_data
