# Private training/use experiment. OFF retains every original object and flag.
set(SARECOMP_LINUX_PGO "OFF" CACHE STRING "Private Linux PGO experiment: OFF, GENERATE or USE")
set_property(CACHE SARECOMP_LINUX_PGO PROPERTY STRINGS OFF GENERATE USE)
set(SARECOMP_LINUX_PGO_PROFILE "" CACHE FILEPATH "Merged measured Linux IR profile")
set(SARECOMP_LINUX_PGO_RUNTIME "" CACHE FILEPATH "Qualified LLVM 21 Linux profile writer; training only")
option(SARECOMP_LINUX_PGO_SPLIT_COLD "Separate profile-cold machine blocks in the private USE build" ON)
if(SARECOMP_LINUX_PGO STREQUAL "OFF")
    return()
endif()
if(NOT SARECOMP_LINUX_PGO MATCHES "^(GENERATE|USE)$")
    message(FATAL_ERROR "Unknown Linux PGO mode")
endif()
if(SARECOMP_LINUX_READ_GROUPS OR SARECOMP_LINUX_PRELOADED_READS OR SARECOMP_LINUX_AOT_STATISTICS OR SARECOMP_LINUX_HARDWARE_FPU OR SARECOMP_LINUX_FPU_REGIONS OR SARECOMP_LINUX_CODE_LAYOUT)
    message(FATAL_ERROR "Linux PGO requires the isolated control configuration")
endif()
if(SARECOMP_LINUX_PGO STREQUAL "GENERATE")
    if(NOT IS_ABSOLUTE "${SARECOMP_LINUX_PGO_RUNTIME}" OR NOT EXISTS "${SARECOMP_LINUX_PGO_RUNTIME}")
        message(FATAL_ERROR "Build the qualified private Linux profile runtime first")
    endif()
    file(SHA256 "${SARECOMP_LINUX_PGO_RUNTIME}" profile_runtime_sha)
    if(NOT profile_runtime_sha STREQUAL "ce13b4fc78a3ffaa87d506b5b87df4d2468481b627aa53fc34e6edd4c30555d9")
        message(FATAL_ERROR "Unqualified profile writer identity")
    endif()
    # Branch layout needs counts, not callbacks on every indirect guest call.
    # Shared host counters may lose concurrent increments; training totals are
    # approximate optimization hints, never gameplay/benchmark counters.
    set(pgo_flags -fprofile-generate -fprofile-update=single
        -mllvm=-enable-name-compression=false -mllvm=-disable-vp=true)
    target_link_libraries(game PRIVATE "${SARECOMP_LINUX_PGO_RUNTIME}")
    target_link_options(game PRIVATE -Wl,-u,__llvm_profile_runtime)
else()
    if(NOT IS_ABSOLUTE "${SARECOMP_LINUX_PGO_PROFILE}" OR NOT EXISTS "${SARECOMP_LINUX_PGO_PROFILE}")
        message(FATAL_ERROR "Linux PGO USE requires an existing merged profile")
    endif()
    set(pgo_flags "-fprofile-use=${SARECOMP_LINUX_PGO_PROFILE}" -Werror=profile-instr-out-of-date -mllvm=-disable-vp=true)
    if(SARECOMP_LINUX_PGO_SPLIT_COLD)
        list(APPEND pgo_flags -fsplit-machine-functions)
    endif()
endif()

include("${SONIC_ROOT}/cmake/LinuxPreloadedReadUnits.cmake")
set(pgo_scope "owner\toriginal\tprivate_copy\n")
set(pgo_count 0)
# No SDL/driver instrumentation and no full AOT rebuild. These owners contain
# the title/execution, memory, draw preparation and native gameplay hot paths.
foreach(owner IN ITEMS sonic_linux_guest sonic_linux_aot_runtime sonic_linux_title
        sonic_linux_services game sonic_linux_graphics sonic_linux_vulkan
        sonic_linux_platform sonic_linux_audio)
    get_target_property(original_sources ${owner} SOURCES)
    set(pgo_sources)
    foreach(source IN LISTS original_sources)
        get_filename_component(name "${source}" NAME)
        set(selected FALSE)
        if(name MATCHES "\\.(cpp|c)$")
            if(NOT owner STREQUAL "sonic_linux_guest" OR name IN_LIST linux_preloaded_units
                    OR name STREQUAL "unit-v8C638FF0-8C639E9C-df982d963eeb3342.cpp")
                set(selected TRUE)
            endif()
        endif()
        if(NOT selected)
            list(APPEND pgo_sources "${source}")
            continue()
        endif()
        get_filename_component(original "${source}" ABSOLUTE BASE_DIR "${SONIC_ROOT}")
        get_filename_component(parent "${original}" DIRECTORY)
        set(copy "${CMAKE_BINARY_DIR}/generated/pgo/${owner}/${name}")
        # Keep the same private source paths in GENERATE and USE so static
        # profile identities match. Original source/object caches remain intact.
        add_custom_command(OUTPUT "${copy}"
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_BINARY_DIR}/generated/pgo/${owner}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${original}" "${copy}"
            DEPENDS "${original}" VERBATIM)
        get_source_file_property(source_includes "${source}" INCLUDE_DIRECTORIES)
        if(NOT source_includes)
            set(source_includes)
        endif()
        set_source_files_properties("${copy}" PROPERTIES INCLUDE_DIRECTORIES "${parent};${source_includes}")
        foreach(property IN ITEMS COMPILE_OPTIONS COMPILE_DEFINITIONS OBJECT_DEPENDS)
            get_source_file_property(original_property "${source}" ${property})
            if(original_property)
                set_source_files_properties("${copy}" PROPERTIES ${property} "${original_property}")
            endif()
        endforeach()
        set_property(SOURCE "${copy}" APPEND PROPERTY COMPILE_OPTIONS ${pgo_flags})
        if(SARECOMP_LINUX_PGO STREQUAL "USE")
            set_property(SOURCE "${copy}" APPEND PROPERTY OBJECT_DEPENDS "${SARECOMP_LINUX_PGO_PROFILE}")
        endif()
        list(APPEND pgo_sources "${copy}")
        string(APPEND pgo_scope "${owner}\t${original}\t${copy}\n")
        math(EXPR pgo_count "${pgo_count}+1")
    endforeach()
    set_property(TARGET ${owner} PROPERTY SOURCES ${pgo_sources})
endforeach()
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/generated/pgo/scope.tsv" CONTENT "${pgo_scope}")
get_target_property(game_definitions game COMPILE_DEFINITIONS)
list(FILTER game_definitions EXCLUDE REGEX "^KATANA_PORT_PGO_MODE_NAME=")
string(TOLOWER "${SARECOMP_LINUX_PGO}" pgo_label)
set_property(TARGET game PROPERTY COMPILE_DEFINITIONS ${game_definitions} "KATANA_PORT_PGO_MODE_NAME=\"${pgo_label}\"")
message(STATUS "Private Linux PGO ${SARECOMP_LINUX_PGO}: ${pgo_count} selected translation units")
