# CPU-feature dispatch is baseline x64; only this independent object needs AVX.
add_library(sonic_palette_batch STATIC "${SONIC_ROOT}/src/sonic_palette_batch.cpp"
    "${SONIC_ROOT}/src/sonic_palette_batch_simd.cpp")
target_include_directories(sonic_palette_batch PUBLIC "${SONIC_ROOT}/src")
if(TARGET sonic_linux_title)
    target_compile_options(sonic_palette_batch PRIVATE -O2 -g0 -frounding-math -ffp-contract=off)
    set_source_files_properties("${SONIC_ROOT}/src/sonic_palette_batch_simd.cpp" PROPERTIES COMPILE_OPTIONS "-mavx2;-mfma")
    target_link_libraries(sonic_palette_batch PUBLIC sonic_linux_aot_runtime)
else()
    target_compile_options(sonic_palette_batch PRIVATE /EHsc /utf-8 /fp:strict)
    set_source_files_properties("${SONIC_ROOT}/src/sonic_palette_batch_simd.cpp" PROPERTIES COMPILE_OPTIONS "/arch:AVX2")
    target_link_libraries(sonic_palette_batch PUBLIC KatanaRecomp::native_port_runtime)
    target_link_libraries(sonic_palette_lighting_tests PRIVATE sonic_palette_batch)
endif()
target_sources(${animation_title} PRIVATE "${SONIC_ROOT}/src/sonic_palette_batch.cpp"
    "${SONIC_ROOT}/src/sonic_palette_batch_simd.cpp")
target_link_libraries(sonic-native-closed-memory-tests PRIVATE sonic_palette_batch)
add_executable(sonic-palette-batch-tests EXCLUDE_FROM_ALL "${SONIC_ROOT}/tools/test_palette_batch.cpp")
target_link_libraries(sonic-palette-batch-tests PRIVATE sonic_palette_batch)
if(TARGET sonic_linux_title)
    target_compile_options(sonic-palette-batch-tests PRIVATE -O2 -g0 -frounding-math -ffp-contract=off)
else()
    target_compile_options(sonic-palette-batch-tests PRIVATE /EHsc /utf-8 /fp:strict)
endif()
