# Two containing units only; internal overrides retain all original routes.
foreach(object_unit IN ITEMS
    unit-v8C09036C-8C09168E-46c0db15f975e3ef.cpp
    unit-v8C091720-8C09276E-f12ea02f8b924edc.cpp)
    set(object_bridge "${CMAKE_BINARY_DIR}/generated/object-activation-bridge/${object_unit}")
    if(TARGET sonic_linux_guest)
        set(object_target sonic_linux_guest)
    elseif(TARGET sonic_ram_regions)
        set(object_target sonic_ram_regions)
    else()
        set(object_target sonic_dispatch)
    endif()
    if(object_target STREQUAL "sonic_dispatch")
        if(NOT SARECOMP_COMPACT_AOT_EXPERIMENT STREQUAL "OFF" OR
           (DEFINED SARECOMP_RAM_READ_EXPERIMENT AND NOT SARECOMP_RAM_READ_EXPERIMENT STREQUAL "OFF"))
            message(FATAL_ERROR "Native object activation requires retained Windows units")
        endif()
        set(object_input "${SONIC_WORKING}/generated/code/${object_unit}")
        target_sources(sonic_dispatch PRIVATE "${object_bridge}")
    else()
        get_target_property(object_sources ${object_target} SOURCES)
        set(object_matches)
        foreach(source IN LISTS object_sources)
            get_filename_component(name "${source}" NAME)
            if(name STREQUAL object_unit)
                list(APPEND object_matches "${source}")
            endif()
        endforeach()
        list(LENGTH object_matches count)
        if(NOT count EQUAL 1)
            message(FATAL_ERROR "Object activation unit must have exactly one active owner")
        endif()
        list(GET object_matches 0 object_input)
        list(REMOVE_ITEM object_sources "${object_input}")
        set_property(TARGET ${object_target} PROPERTY SOURCES ${object_sources} "${object_bridge}")
        get_source_file_property(object_includes "${object_input}" INCLUDE_DIRECTORIES)
        if(object_includes)
            set_source_files_properties("${object_bridge}" PROPERTIES INCLUDE_DIRECTORIES "${object_includes};${SONIC_ROOT}/src")
        else()
            set_source_files_properties("${object_bridge}" PROPERTIES INCLUDE_DIRECTORIES "${SONIC_ROOT}/src")
        endif()
    endif()
    if(NOT TARGET sonic_linux_guest)
        set_source_files_properties("${object_bridge}" PROPERTIES COMPILE_OPTIONS "/fp:strict;/bigobj")
    endif()
    add_custom_command(OUTPUT "${object_bridge}"
        COMMAND "${Python3_EXECUTABLE}" "${SONIC_ROOT}/tools/prepare-object-activation-bridge.py"
            --source-root "${SONIC_WORKING}/generated" --input "${object_input}" --output "${object_bridge}"
        DEPENDS "${SONIC_ROOT}/tools/prepare-object-activation-bridge.py" "${object_input}"
            "${SONIC_WORKING}/generated/.katana-generated-artifacts" VERBATIM)
endforeach()
