add_library(sonic_audio_status STATIC "${SONIC_ROOT}/src/sonic_audio_status.cpp")
target_include_directories(sonic_audio_status PUBLIC "${SONIC_ROOT}/src")
add_executable(sonic-audio-status-tests EXCLUDE_FROM_ALL "${SONIC_ROOT}/tools/test_audio_status.cpp")
target_link_libraries(sonic-audio-status-tests PRIVATE sonic_audio_status)
add_executable(sonic-sound-command-tests EXCLUDE_FROM_ALL "${SONIC_ROOT}/tools/test_sound_commands.cpp")
target_include_directories(sonic-sound-command-tests PRIVATE "${SONIC_ROOT}/src")
if(TARGET sonic_linux_title)
    target_include_directories(sonic_audio_status PRIVATE "${SONIC_LINUX_SDK}/src/runtime")
    target_compile_options(sonic_audio_status PRIVATE -O2 -g0)
    target_link_libraries(sonic_audio_status PUBLIC sonic_linux_services)
    target_link_libraries(sonic_linux_title PUBLIC sonic_audio_status)
    target_include_directories(sonic-audio-status-tests PRIVATE "${SONIC_LINUX_SDK}/src/runtime")
    target_compile_options(sonic-audio-status-tests PRIVATE -O2 -g0)
    target_compile_options(sonic-sound-command-tests PRIVATE -O2 -g0)
    target_sources(sonic-sound-command-tests PRIVATE "${SONIC_ROOT}/src/sonic_presentation.cpp")
    target_link_libraries(sonic-sound-command-tests PRIVATE sonic_linux_services)
else()
    target_include_directories(sonic_audio_status PRIVATE "${audio_output}")
    add_dependencies(sonic_audio_status sonic_audio_output)
    target_compile_options(sonic_audio_status PRIVATE /EHsc /utf-8)
    target_link_libraries(sonic_audio_status PUBLIC KatanaRecomp::native_port_runtime)
    # The pinned product link contract admits title code through the existing
    # adapter owner, not a new runtime library identity.
    target_sources(katana_native_title_adapter PRIVATE "${SONIC_ROOT}/src/sonic_audio_status.cpp")
    target_include_directories(katana_native_title_adapter PRIVATE "${audio_output}")
    add_dependencies(katana_native_title_adapter sonic_audio_output)
    target_sources(sonic-audio-status-tests PRIVATE $<TARGET_OBJECTS:sonic_audio_output>)
    target_include_directories(sonic-audio-status-tests PRIVATE "${audio_output}")
    target_compile_options(sonic-audio-status-tests PRIVATE /EHsc /utf-8)
    target_link_libraries(sonic-audio-status-tests PRIVATE ole32 winmm)
    target_sources(sonic-sound-command-tests PRIVATE "${SONIC_ROOT}/src/sonic_presentation.cpp"
        $<TARGET_OBJECTS:sonic_audio_buses> $<TARGET_OBJECTS:sonic_audio_output>)
    target_compile_options(sonic-sound-command-tests PRIVATE /EHsc /utf-8 /fp:strict)
    target_link_libraries(sonic-sound-command-tests PRIVATE KatanaRecomp::native_port_runtime ole32 winmm)
endif()
