set(inverse_trig_dir "${CMAKE_BINARY_DIR}/generated/inverse-trig")
set(inverse_trig_outputs "${inverse_trig_dir}/inverse-identities.inc" "${inverse_trig_dir}/inverse-members.inc" "${inverse_trig_dir}/inverse-bodies.inc")
add_custom_command(OUTPUT ${inverse_trig_outputs}
    COMMAND "${Python3_EXECUTABLE}" "${SONIC_ROOT}/tools/prepare-inverse-trig.py"
        --ram "${SONIC_ROOT}/.local/baseline/r354/native-content/postpal-main-ram-native-ready.bin"
        --output "${inverse_trig_dir}"
    DEPENDS "${SONIC_ROOT}/tools/prepare-inverse-trig.py" "${SONIC_ROOT}/tools/prepare_collision_candidates.py"
        "${SONIC_ROOT}/.local/baseline/r354/native-content/postpal-main-ram-native-ready.bin" VERBATIM)
if(TARGET sonic_linux_title)
    set(inverse_trig_title sonic_linux_title)
    set(inverse_trig_guest sonic_linux_guest)
    add_executable(sonic_atan_math_tests EXCLUDE_FROM_ALL "${SONIC_ROOT}/tools/test_atan_math.cpp" "${SONIC_ROOT}/src/sonic_atan_math.cpp"
        "${SONIC_LINUX_SDK}/src/runtime/dynamic_interpreter.cpp"
        "${SONIC_LINUX_SDK}/src/decoder/decoder.cpp" "${SONIC_LINUX_SDK}/src/decoder/instruction_metadata.cpp"
        $<TARGET_OBJECTS:sonic_linux_memory>)
    target_include_directories(sonic_atan_math_tests PRIVATE "${SONIC_ROOT}/src" "${CMAKE_BINARY_DIR}/generated/fpu-body")
    target_compile_options(sonic_atan_math_tests PRIVATE -O2 -g0 -frounding-math -ffp-contract=off)
    target_link_options(sonic_atan_math_tests PRIVATE -Wl,--gc-sections)
    target_link_libraries(sonic_atan_math_tests PRIVATE sonic_linux_services)
else()
    set(inverse_trig_title katana_native_title_adapter)
    if(SARECOMP_NATIVE_MEMORY_CAPABILITY)
        get_target_property(inverse_libraries sonic_atan_math_tests LINK_LIBRARIES)
        set_property(TARGET sonic_atan_math_tests PROPERTY LINK_LIBRARIES sonic_internal_diagnostics ${inverse_libraries})
    endif()
    if(TARGET sonic_ram_regions)
        set(inverse_trig_guest sonic_ram_regions)
    else()
        set(inverse_trig_guest sonic_dispatch)
    endif()
endif()
foreach(target IN ITEMS ${inverse_trig_title} sonic_atan_math_tests)
    target_sources(${target} PRIVATE ${inverse_trig_outputs})
    target_include_directories(${target} PRIVATE "${inverse_trig_dir}")
endforeach()
set(inverse_trig_oracle "${CMAKE_BINARY_DIR}/generated/inverse-trig-bridge/private-reference.cpp")
add_custom_command(OUTPUT "${inverse_trig_oracle}"
    COMMAND "${Python3_EXECUTABLE}" "${SONIC_ROOT}/tools/prepare-inverse-trig-bridge.py"
        --source-root "${SONIC_WORKING}/generated" --output "${inverse_trig_oracle}"
    DEPENDS "${SONIC_ROOT}/tools/prepare-inverse-trig-bridge.py" "${SONIC_WORKING}/generated/.katana-generated-artifacts" VERBATIM)
get_target_property(inverse_trig_test_sources sonic_atan_math_tests SOURCES)
list(FILTER inverse_trig_test_sources EXCLUDE REGEX "test_atan_math.cpp$")
add_executable(sonic-inverse-trig-aot-tests EXCLUDE_FROM_ALL "${SONIC_ROOT}/tools/test_inverse_trig_aot.cpp" ${inverse_trig_test_sources} "${inverse_trig_oracle}")
foreach(property IN ITEMS INCLUDE_DIRECTORIES COMPILE_OPTIONS COMPILE_DEFINITIONS LINK_LIBRARIES LINK_OPTIONS)
    get_target_property(value sonic_atan_math_tests ${property})
    if(value)
        set_property(TARGET sonic-inverse-trig-aot-tests PROPERTY ${property} "${value}")
    endif()
endforeach()
target_include_directories(sonic-inverse-trig-aot-tests PRIVATE "${SONIC_WORKING}/generated/include")
if(NOT TARGET sonic_linux_guest)
    set_source_files_properties("${inverse_trig_oracle}" PROPERTIES COMPILE_OPTIONS "/fp:strict;/bigobj")
endif()
foreach(unit IN ITEMS unit-v8C10CDDC-8C10DA5C-cb14c3e2f790eaff.cpp unit-v8C10DB04-8C10EB80-b3bbbddd2dccf359.cpp)
    set(output "${CMAKE_BINARY_DIR}/generated/inverse-trig-bridge/${unit}")
    get_target_property(sources ${inverse_trig_guest} SOURCES)
    set(matches)
    foreach(source IN LISTS sources)
        get_filename_component(name "${source}" NAME)
        if(name STREQUAL unit)
            list(APPEND matches "${source}")
        endif()
    endforeach()
    list(LENGTH matches count)
    if(count EQUAL 0 AND inverse_trig_guest STREQUAL "sonic_dispatch")
        set(input "${SONIC_WORKING}/generated/code/${unit}")
        target_sources(${inverse_trig_guest} PRIVATE "${output}")
    elseif(count EQUAL 1)
        list(GET matches 0 input)
        list(REMOVE_ITEM sources "${input}")
        set_property(TARGET ${inverse_trig_guest} PROPERTY SOURCES ${sources} "${output}")
    else()
        message(FATAL_ERROR "Inverse trig requires exactly one retained owner")
    endif()
    get_source_file_property(includes "${input}" INCLUDE_DIRECTORIES)
    if(NOT includes)
        set(includes)
    endif()
    set_source_files_properties("${output}" PROPERTIES INCLUDE_DIRECTORIES "${includes};${SONIC_ROOT}/src")
    if(NOT TARGET sonic_linux_guest)
        set_source_files_properties("${output}" PROPERTIES COMPILE_OPTIONS "/fp:strict;/bigobj")
    endif()
    add_custom_command(OUTPUT "${output}"
        COMMAND "${Python3_EXECUTABLE}" "${SONIC_ROOT}/tools/prepare-inverse-trig-bridge.py"
            --source-root "${SONIC_WORKING}/generated" --input "${input}" --output "${output}"
        DEPENDS "${SONIC_ROOT}/tools/prepare-inverse-trig-bridge.py" "${input}"
            "${SONIC_WORKING}/generated/.katana-generated-artifacts" VERBATIM)
endforeach()
